# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run:
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build project
        run: npm run build
        env:
          CI: true
      - name: Create tarball
        run: npm pack && mv aduh95-toml-*.tgz aduh95-toml-unreleased.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: npm-tarball
          path: aduh95-toml-unreleased.tar.gz

  test-node:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node: [12.17.0, 14]
        supportsESM: [true]
        include:
          - node: 10
            supportsESM: false

    steps:
      - uses: actions/checkout@v2
      - name: Download tarball
        uses: actions/download-artifact@v1
        with:
          name: npm-tarball
      - name: Extract tarball
        run: >
          tar --strip-components=1 -xzf
          npm-tarball/aduh95-toml-unreleased.tar.gz
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        env:
          RUNNER_TEMP: /tmp
        with:
          node-version: ${{ matrix.node }}
      - name: Create symlink for Node version with no self-reference support
        if: matrix.supportsESM == false
        run: >
          node -e 'require.resolve("@aduh95/toml")' || ( mkdir -p
          node_modules/@aduh95 && ln -s $GITHUB_WORKSPACE
          node_modules/@aduh95/toml)
      - name: Run tests CommonJS
        run: npm run test:cjs
      - name: Run tests ESM
        if: matrix.supportsESM
        run: npm run test:esm

  test-deno:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node: [1.0.3]

    steps:
      - uses: actions/checkout@v2
      - name: Download tarball
        uses: actions/download-artifact@v1
        with:
          name: npm-tarball
      - name: Extract tarball
        run: >
          tar --strip-components=1 -xzf
          npm-tarball/aduh95-toml-unreleased.tar.gz
      - name: Install Deno ${{ matrix.deno }}
        run:
          curl -fsSL https://deno.land/x/install/install.sh | sudo
          DENO_INSTALL=/usr/local sh -s ${{ matrix.deno }}
      - name: Run tests
        run: npm run test:deno
