# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run:
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build project
        run: npm run build
        env:
          CI: true
      - name: Create tarball
        run: npm pack && mv aduh95-toml-*.tgz aduh95-toml-unreleased.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: aduh95-toml-unreleased-${{ github.sha }}.tar.gz
          path: aduh95-toml-unreleased.tar.gz

  test-node:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Download tarball
        uses: actions/download-artifact@v1
        with:
          name: aduh95-toml-unreleased-${{ github.sha }}.tar.gz
      - name: Extract tarball
        run:
          tar --strip-components=1 -xzf aduh95-toml-unreleased-${{ github.sha
          }}.tgz
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        env:
          RUNNER_TEMP: /tmp
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        run: npm run test:node

  test-deno:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node: [1.0.3]

    steps:
      - uses: actions/checkout@v2
      - name: Download tarball
        uses: actions/download-artifact@v1
        with:
          name: aduh95-toml-unreleased-${{ github.sha }}.tar.gz
      - name: Extract tarball
        run:
          tar --strip-components=1 -xzf aduh95-toml-unreleased-${{ github.sha
          }}.tgz
      - name: Install Deno ${{ matrix.deno }}
        run:
          curl -fsSL https://deno.land/x/install/install.sh | sudo
          DENO_INSTALL=/usr/local sh -s ${{ matrix.deno }}
      - name: Run tests
        run: npm run test:deno
